version: '2'

services:
  mysql:
    build:
      dockerfile: './mysql.dockerfile'
      context: '.'
    environment:
      MYSQL_DATABASE: ny_cab_data
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3308:3306